### PR TITLE
Workflow to Reduce Notifications 🚀

### LINKED ISSUE #1390: Lock New Issues : Workflow to Reduce Notifications and Support Maintainers
### Description

**As a repository maintainer, I propose the implementation of a workflow that aims to minimize notifications and enhance the support provided to maintainers. This workflow will automatically lock newly opened issues and provide guidance to contributors.**

### Screenshots

```
name: 'Lock new issues'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues
        uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          exclude-issue-labels: 'gssoc23.'
          process-only: 'issues'
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label `gssoc23`. If you're participating in GSSoC'23, please add the `gssoc23` label to your issue.

```

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Closes

Closes #1390 

## Description

 I implemented a workflow that aims to minimize notifications and enhance the support provided to maintainers. This workflow will automatically lock newly opened issues and provide guidance to contributors.

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @Vaishnavi-Patil2211  PLease review the pr and merge it  :)

**Comment by Nishitbaria** [comment]
**Hey @Vaishnavi-Patil2211  Please Review This Issue and merge it**

**Comment by Vaishnavi-Patil2211** [comment]
It's facing same error

**Comment by Nishitbaria** [comment]
Hey @Vaishnavi-Patil2211   checkout ,my video i have explained the everythins 


[screen-capture. webm](https://github.com/apoorvaron/Shorty/assets/85815172/59967c46-b187-4806-893b-5c415fc94976)

**Comment by Nishitbaria** [comment]
@Vaishnavi-Patil2211  you have to give permission for that


image

**Comment by Nishitbaria** [comment]
### **Hey @Vaishnavi-Patil2211   If you facing still problems then I will provide you with code** 

### **step-1 go to `.github/workflows/`**

### **step-2 copy the following code  

```
name: 'Lock new issues'

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Lock issues
        uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          exclude-issue-labels: 'gssoc23.'
          process-only: 'issues'
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce notifications, issues are locked. Your issue will be unlocked when we add the label `gssoc23`. If you're participating in GSSoC'23, please add the `gssoc23` label to your issue.
```

### **step-3 Create **`lock.yml`** file paste code and save it**  


### **Now its workflow work well happy hacking   ✨**

**Pull request merged**
