### PR TITLE
feat: Toggle button added

### LINKED ISSUE #116: feat: Toggle button
Hello!!

I want to add a toggle button for switching light and dark theme. Can I work on this for gssoc?

@akshathar-navada

### PR DESCRIPTION
**Pull request by SINJINI-G**
**Description**
toggle button has been added that changes the theme between dark and light.

This PR fixes #116

Kindly review the PR.

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @SINJINI-G , we will review and merge it soon!

**Comment by akshathar-navada** [comment]
@SINJINI-G Your commit changes only the navbar to light or dark,that would be fine. I appreciate your contribution, if there is any other improvement,pls go ahead

**Comment by SINJINI-G** [comment]
Thanks for the feedback.. Looking forward to contributing more!!

**Comment by SINJINI-G** [comment]
Hi @akshathar-navada !! It will be really helpful if you could add the gssoc and the level tag.. since the leader board opens really soon.

**Pull request merged**
