### PR TITLE
About us in footer is not working

### PR DESCRIPTION
**Pull request by abhishekbhonde**
**Description**

About us in footer is not working

**Notes for Reviewers**

### CODE REVIEW

**Comment by akshathar-navada** [comment]
@abhishekbhonde Please add the required screenshots ,explaining the changes before and after!

**Comment by abhishekbhonde** [comment]
> @abhishekbhonde Please add the required screenshots ,explaining the changes before and after!
When we were clicking on about us it was not directing to about section

Screenshot 2023-05-25 011153

after solving it.


Screenshot 2023-05-25 011214

**Comment by akshathar-navada** [comment]
Oh ya @abhishekbhonde , we review and merge it soon!

**Comment by akshathar-navada** [comment]
Hey @abhishekbhonde , thanks for correcting that. But, due to this the text of OS-CODE near the logo was pushed to top, which was not needed, so i reverted back.

**Review by akshathar-navada — COMMENTED** [review]
Hey @abhishekbhonde , thanks for correcting that. But, due to this the text of OS-CODE near the logo was pushed to top, which was not needed, so i reverted back. Please open a another PR< where u will only change the linking of BAOOUT_US in footer and not others

**Comment by abhishekbhonde** [comment]
Ok np I will look into that.

**Pull request merged**
