### PR TITLE
fixed navbar dropdown lists position in mobile view 

### PR DESCRIPTION
**Pull request by abhiraj-ku**
**Description**
This PR is Regarding issue #525.
I have fixed the position of nav-bar drop-down in mobile view and also fixed some comments spelling mistakes in main.js file

Thanks in Advance

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @abhiraj-ku , it would be great if u add the screenshot of that navbar thingy to review!

**Comment by abhiraj-ku** [comment]
sure @akshathar-navada 
oscode mobile2

**Comment by akshathar-navada** [comment]
Thanks @abhiraj-ku

**Comment by abhiraj-ku** [comment]
Thanks @akshathar-navada  for merging . I will look to contribute more to this project

**Comment by akshathar-navada** [comment]
> Thanks @akshathar-navada for merging . I will look to contribute more to this project

It's our pleasure to review and merge your PR  :)

**Pull request merged**
