### PR TITLE
Improving Contact Form

### LINKED ISSUE #651: To enchane the ui of contact form
### Current Behavior
Currently the contact form's UI is very simple

### Desired Behavior
To make it look good with the help of HTML, CSS and JS

### Screenshots / Mockups
N/A

---

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
## Closes
 To enchane the ui of contact form #651 

Closes #651

## Description

- The background Color of the contact form is changed
- Hover effect of button is improved
- shadows on hover are enhanced

## Screenshots

**Before**

Screenshot 2023-06-13 220222

**After**

Screenshot 2023-06-13 220323

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Review by akshathar-navada — CHANGES_REQUESTED** [review]
Hey @DhairyaMajmudar , there are conflicts in your PR, please pull the repo properly and then make required changes. And also pls upload the screenshot of complete CONTACT section.

**Comment by DhairyaMajmudar** [comment]
Ok @akshathar-navada sir I will do the same

**Comment by DhairyaMajmudar** [comment]
@akshathar-navada ma'am I have committed the required changes pls. review them.

**Comment by akshathar-navada** [comment]
Let the existing one be. If there is anything else, u would like tow ork on, pls go ahead

**Pull request closed without merging**
