### PR TITLE
Updated Redirection Button

### PR DESCRIPTION
**Pull request by swarnade**
**Description**

This PR fixes #

**Notes for Reviewers**

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Thanks @swarnade , we will review and merge it soon!

**Review by akshathar-navada — CHANGES_REQUESTED** [review]
Hey, I don't think u have made any changes. I had mentioned to link it to "JOIN US" section and also pls mention the issue no, so that it would easy for us . SO,pls link the GET STARTED to JOIN US section and not contact section

**Comment by swarnade** [comment]
Looking Into It

**Review by swarnade — COMMENTED** [review]
Updated From Contact Us To Join Us

**Comment by swarnade** [comment]
Closes Issue #399

**Review by akshathar-navada — CHANGES_REQUESTED** [review]
hey @swarnade , actually the hovering effect of those buttons have been changed now. Like the <span> is added , can u pls look into that. The redirection thing which u have changed is fine, but in order to have those hovering effects also, we want u to pull the repo properly and then make this redirection change. We will review and merge it soon:)
Thank you!!

**Comment by swarnade** [comment]
Okh Looking Into It

**Review by swarnade — COMMENTED** [review]
Done All Changes

**Comment by akshathar-navada** [comment]
> Done All Changes

Hey @swarnade , u didn't change anything, the commit is same as previous
Ok I will tell u.....
Check 139 and 140th lines in this
Screenshot (447)

Those lines should be there, the <span> is not there in your commit. I mean the button content must be wrapped inside the span tag. Instead of directing it to contact section, lead that to join-us

**Comment by swarnade** [comment]
Acctually @akshathar-navada Due To Multiple Commits And Changes It Is Getting Confused

I Am Closing This Pull Request And Issueing a Fresh Pull Request

**Pull request closed without merging**
