### PR TITLE
UI Fixed

### PR DESCRIPTION
**Pull request by SubhamB2003**
## Closes
Issue Solved: #860 

@Divesh2003 Can you please review it

image

Closes #issue_number

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by SubhamB2003** [comment]
@Vaishnavi-Patil2211 Hey please also the level here otherwise they are not counting this

**Comment by Vaishnavi-Patil2211** [comment]
> @Vaishnavi-Patil2211 Hey please also add the level here otherwise they are not counting this

Done !!

**Comment by SubhamB2003** [comment]
> > @Vaishnavi-Patil2211 Hey please also add the level here otherwise they are not counting this
> 
> Done !!

@Vaishnavi-Patil2211 🙂Hey don't remove the GSSOC'23 level both are needed to counting

**Comment by SubhamB2003** [comment]
> > @Vaishnavi-Patil2211 Hey please also add the level here otherwise they are not counting this
> 
> Done !!

thanks

**Pull request merged**
