### PR TITLE
Home Section need some Improvement #47 Fixed

### LINKED ISSUE #47: Home Section need some Improvement
Home Section looks like wired in terms of UI i think it need some improvement. Hey @FuryACE007 @vinitvijal @ng169 @akashgreninja @rashi2911 assign me this so that I will improve the Home section.
Screenshot (226)

### PR DESCRIPTION
**Pull request by 9520prashant**
Home Section UI has been updated. Now it looks very user friendly.

This PR fixes #47 issue.

Screenshot (242)

### CODE REVIEW

**Comment by 9520prashant** [comment]
The theme of Home Section has been taken according to animation of text in home section.

**Comment by akshathar-navada** [comment]
Hey @9520prashant , it's nice. Your commit has few conflicts through which we won't be able to merge. can u pls pull the repo properly nd then make required changes:)

**Comment by 9520prashant** [comment]
Ok I will work on it

**Comment by 9520prashant** [comment]
Sure again I will definitely work on it and redesign the home section.

**Pull request closed without merging**
