### PR TITLE
Hovering effect of discord favicon in the footer section 

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
before ------

image

after -------

image

Please consider this GSSOC_23 [contributor]  : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
@OSCode-Community   once  check  this and please  merge  it under  GSSOC_23  contributor  : )

**Comment by akshathar-navada** [comment]
Hey @Bharath-KumarReddy , I would suggest u to just change the background color of it when hovered instead of discord icon color getting changed. And also there are conflicts in your commit, pls pull the repo properly and then make required changes

**Comment by Bharath-KumarReddy** [comment]
@akshathar-navada   yes  sure  i can change  the background color  of discord  when it is hovered  instead of discord icon color getting changed   

Like this -------


image


once  Please  check  this  : )  and    thank you for your  suggestion  for improving this    : )

**Comment by akshathar-navada** [comment]
I will be closing this issue ,as it was raised and assigned to other person!

**Pull request closed without merging**
