### PR TITLE
Updated "Join Us" Section

### PR DESCRIPTION
**Pull request by iamRabia-N**
**Description**
This PR contains the code of updated "Join Us" Section.

**Output Sample**
oscode pr3 ss

### CODE REVIEW

**Comment by iamRabia-N** [comment]
This PR is the result of following issue:
**"Join Us" Section Text Alignment Improvement #484**

**Comment by Divesh2003** [comment]
@iamRabia-N There are some conflicts in your PR. Kindly resolve it....

**Comment by iamRabia-N** [comment]
I have added a class name for styling in the index.html due to which this message arrived. Can you tell me how to resolve this error without removing that class?

**Comment by iamRabia-N** [comment]
@Divesh2003 Done with resolving conflict. You can review now.

**Pull request merged**
