### PR TITLE
Better Navbar with color clarity and positioning of the contact us button at a better position

### PR DESCRIPTION
**Pull request by shramanpaul**
**Description**

This PR fixes #
1.THE COLOR OF CONTACT US USE TO GET HIDDEN DUE TO THE SAME COLOR {now fixed}
2.CONTACT US BUTTON WAS IN A WEIRD POSITON {now fixed}
**Notes for Reviewers**

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @shramanpaul , can u pleasee add the required screenshot, so it will be easy for us to review..

**Comment by shramanpaul** [comment]
yes
1. positioning of the contact us button done in the same row in the navbar
      
positioning of the contact us button done in the same row in the navbar
2. color of the contact us when it is active in the region fixed
       
color of the contact us when it is active in the region fixed

**Comment by shramanpaul** [comment]
I have resolved the conflicts now you can review and merge

**Comment by akshathar-navada** [comment]
Hey @shramanpaul , actually now the navbar is changed a bit, pls check out. We prefer the existing one. 
If there is any other improvements u would like to make , pls go ahead!
Thank you!!

**Pull request closed without merging**
