### PR TITLE
📝 Docs: Dark/Light Responsive Logo

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
### Description
- This is PR is about adding responsive dark/light logo, the logo will change according to the user's theme preference
- This PR fixes: #530 

### Notes for Reviewers
- I added inverted image on the `assets/img` directory
- You can see the changes in below screenshot

| LIGHT | DARK |
|  :-----:   | :-----:  |
|  |  |

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Thanks @0xabdulkhalid , we will review and merge it soon!

**Comment by akshathar-navada** [comment]
Hey @0xabdulkhalid , in light theme it works. But for some reason the OS-Code logo is not visible in the black theme readme. Can u pls check tis out!

Screenshot (448)

**Comment by 0xabdulkhalid** [comment]
Hello @akshathar-navada, the both images are finely loaded there are no issue.

BTW: Please add `gssoc23` and necessary `level` label so that the `GSSoC`'s Backend can count this Contribution

Thanks!

**Comment by akshathar-navada** [comment]
> Hello @akshathar-navada, the both images are finely loaded there are no issue.
> 
> BTW: Please add `gssoc23` and necessary `level` label so that the `GSSoC`'s Backend can count this Contribution
> 
> Thanks!

Then why was it showing alt text instead of the logo in above screenshot?

**Pull request merged**
