### PR TITLE
copyrightincontributorpage

### LINKED ISSUE #1249: [Bug]: the copyright contributor
### Description

the copy right of contributor page is not same as index page

### Expected Behavior

we can keep same behaviour

### Show us the trouble with screenshots

Screenshot (551)

### Which browsers are affected?

Chrome

### Which OS are affected?

Windows

### Enter the version of your web browser

Version 115.0.5790.102 (Official Build) (64-bit)

### Device?

Desktop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by khadar1020**
## Closes

Closes #1249

## Description

i have changed the copyright of contributor page as home page and made it interactive in phone mode also 

## Screenshots

Screenshot (553)

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by khadar1020** [comment]
can you plese review my [r @Vaishnavi-Patil2211

**Comment by khadar1020** [comment]
can you please review my pr @Vaishnavi-Patil2211

**Comment by khadar1020** [comment]
can you please review my pr @Vaishnavi-Patil2211

**Comment by Vaishnavi-Patil2211** [comment]
It's already done Don't tag me again n again if it's already done

**Pull request merged**
