### PR TITLE
Added Login and Signup Page

### LINKED ISSUE #691: Add login And signup page
### Desired Behavior
I want toa dd the login and signup page to the website.

### Screenshots / Mockups

---

### PR DESCRIPTION
**Pull request by sumitkr2000**
## Closes

Closes #691 

## Description

Hey, I have added a login and a signup page. Please review my pr and merge it. Thank you!

## Screenshots

- Login page:-

image

- Signup Page:-

image

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by sumitkr2000** [comment]
@akshathar-navada what about tags?

**Comment by akshathar-navada** [comment]
Hey @sumitkr2000 , grt work. Wanted to know where have you linked those pages?
It is linked to get started and contact section uh? Y is that  not redirecting?

**Comment by akshathar-navada** [comment]
Ya, got it now!

**Comment by sumitkr2000** [comment]
> Hey @sumitkr2000 , grt work. Wanted to know where have you linked those pages? It is linked to get started and contact section uh? Y is that not redirecting?

Hey, the login lage is linked to the last icon. And of the user has no account from the login page there ks an option to signup.

**Comment by sumitkr2000** [comment]
By clicking on signup they will be redirected to signup page. The only thing remaining is now the authentication part.

**Comment by akshathar-navada** [comment]
> By clicking on signup they will be redirected to signup page. The only thing remaining is now the authentication part.

Yep! got that, If u can work on authentication go ahead!

**Comment by sumitkr2000** [comment]
I ma travelling currently...will let you know if i am free.

**Pull request merged**
