### PR TITLE
Updated Corousel-Controls in Testimonials Section

### PR DESCRIPTION
**Pull request by AdityaLahane-2003**
### Updated Carousel-Controls in Testimonials Section 
- Updated, it's  looking good and handy to use for users !  

**Before**
coro1

**After**
corousal

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Yea, looks good. We will merge this soon. But please also take a look into your previous commit, there was an error through which evnt page was not loading

**Comment by AdityaLahane-2003** [comment]
Okay! I'll look into that 
Thank you for merging!

**Comment by AdityaLahane-2003** [comment]
Should I create a new PR? for the previous change, I've solved that issue now, loading of the event page.
@akshathar-navada

**Comment by AdityaLahane-2003** [comment]
I've created new PR for the previous issue, please check and merge it ! 
@akshathar-navada

**Comment by AdityaLahane-2003** [comment]
Can you please label this PR also as GSSoC'23.

**Pull request merged**
