### PR TITLE
Update chapter.html

### LINKED ISSUE #1079: Chapter page need ui improvement
### Description

chapter page needs improvement

### Expected Behavior

I remember that the chapter page used to have a different appearance, similar to what is shown in the screenshot

254763677-b0bc2dbd-e880-4a23-a3a4-b9423d10e1e8

### Show us the trouble with screenshots

image

### Which browsers are affected?

_No response_

### Which OS are affected?

_No response_

### Enter the version of your web browser

chrome

### Device?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RitiChandak**
## Closes

Closes #1079 

## Screenshots

image
image
image
image

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@Vaishnavi-Patil2211 please review the pr i tried my best to revive the code

**Comment by RitiChandak** [comment]
hi please allot me other issue

**Comment by Vaishnavi-Patil2211** [comment]
Which one

**Comment by RitiChandak** [comment]
#1048 #1073  #1077 #1087 #1088 #1089

**Pull request merged**
