### PR TITLE
changed background in chapters

### LINKED ISSUE #384: making a better presentation of college chapters
### Current Behavior

The current ui of the website is of chapters page is not promising and can be made better with fonts and images.

### Desired Behavior

I can add good fonts and better images to it's background to make it look attractive.

### Screenshots / Mockups

---

### PR DESCRIPTION
**Pull request by AishwaryaIGDTUW**
**Description**

This PR fixes #384 

**Notes for Reviewers**
the background for college chapters has been changed

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Can u pls add required screenshots @AishwaryaIGDTUW

**Comment by AishwaryaIGDTUW** [comment]
image   (after changes)


image   (before changes)

**Comment by akshathar-navada** [comment]
Thanks @AishwaryaIGDTUW

**Comment by AishwaryaIGDTUW** [comment]
you are welcome

**Pull request merged**
