### PR TITLE
chapter page improved

### LINKED ISSUE #1611: UI of chapter page needs improvement
### What feature?

chapter page ui need to be improve 

### Show us the magic with screenshots

image
image
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by RitiChandak**
## Closes

Closes #1611 

## Description

1. the distored page is improved
2. navbar is changed and improved
3. logo of os code added in navbar
4. footer navbar is improved
5. repeative college cards removed
6. style the collge card 
7. page is responsive 
8. os code logo added in tab
## Screenshots

image
image
image
image
image

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by RitiChandak** [comment]
@Divesh2003 please review the pr

**Comment by RitiChandak** [comment]
@Divesh2003 @Vaishnavi-Patil2211 please review the pr

**Comment by Divesh2003** [comment]
@RitiChandak Bro can you fix the conflicts

Conflicting files
chapters/chapter.html

**Comment by RitiChandak** [comment]
@Divesh2003 solved it please merge thi pr

**Comment by RitiChandak** [comment]
@Divesh2003

**Pull request merged**
