### PR TITLE
refractor: styles of contributors page ✨

### LINKED ISSUE #1342: [Refactor]: css file of contributors page ✨
### File Name

contributors/styles.css

### Reason for Refactoring the Code

- The revamped design has been reverted due to latest pr merge for refracting the css file.

### Checklist

- [X] I have checked the existing [issues](https://github.com/rupali-codes/LinksHub/issues).
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md).
- [X] The changes don't break the code and don't introduce new functionality.
- [X] I am willing to work on this issue (optional).
- [X] I am a GSSoC23 contributor.

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Description
- Refractor css file with best practices for Contributors Page.

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@Vaishnavi-Patil2211 your review is highly appreciated 🙌🏻

**Comment by Vaishnavi-Patil2211** [comment]
Solve merge conflict first

**Comment by Vaishnavi-Patil2211** [comment]
Solve the merge conflict first

**Comment by 0xabdulkhalid** [comment]
Conflicts have been resolved ⚡

@Vaishnavi-Patil2211

**Pull request merged**
