### PR TITLE
Image updated.

### PR DESCRIPTION
**Pull request by Sathvik902**
Please accept the PR. I have added a more clear Image to the site.

### CODE REVIEW

**Comment by akshathar-navada** [comment]
@Sathvik902 Can u please add the required screenshot?

**Comment by Sathvik902** [comment]
Sure!

image

**Comment by Sathvik902** [comment]
Isn't it good? @akshathar-navada

**Comment by Sathvik902** [comment]
Please Add 'Gssoc'23' label to the issue #36

**Comment by akshathar-navada** [comment]
> Isn't it good? @akshathar-navada

Hey @Sathvik902 , can u please try to add a image which includes group of people and not just two. Ofcourse this is good, but needed in that way.
Thank you!

**Comment by Sathvik902** [comment]
Sure.

**Comment by Sathvik902** [comment]
How about now? @akshathar-navada 

image

**Comment by akshathar-navada** [comment]
Great!!, we will review and merge it soon:)
Thank you @Sathvik902

**Pull request merged**
