### PR TITLE
feat: automating author assign pr to author 💡

### LINKED ISSUE #1439: [Feat]: PR Auto Assign Feature, Automate assigning process 🚀✨
## Description
- To streamline our contribution process and show appreciation to our contributors, we aim to automate the assignment of Pull Requests (PRs) to their respective authors as soon as they are opened. 
- By implementing an Auto-Assign GitHub Workflow, we can efficiently allocate ownership of the PRs and ensure a smoother collaboration experience for everyone involved.

## Key Points to Address
1. **Auto-Assignment Logic:** Create a workflow that automatically assigns the PR to the author who opened it. This logic should trigger immediately upon PR creation to minimize any delay in assignment.

2. **Error Handling:** Account for scenarios where the author may not be explicitly defined or may not have sufficient permissions to be assigned. Implement appropriate error handling and notifications to address such cases gracefully.

3. **Collaborator Verification:** Ensure that the assigned author is a valid collaborator on the repository to avoid any potential unauthorized assignment.

4. **Testing and Validation:** Thoroughly test the workflow on a test repository and validate its functionality under different scenarios to ensure accuracy and reliability.

5. **Documentation:** Provide clear and concise documentation on how the Auto-Assign GitHub Workflow works, its purpose, and how to troubleshoot potential issues.

6. **Feedback and Iteration:** Seek feedback from contributors and maintainers during the implementation phase to make improvements and address any concerns that arise.

## Expected Outcome
- The introduction of the Auto-Assign GitHub Workflow will simplify the process of PR ownership assignment, ensuring that contributors receive proper recognition for their contributions without manual intervention.
-  This automation will foster a more efficient and welcoming environment for our open-source community, encouraging continued collaboration and participation.

Let's work together to set up this workflow and make our contribution process even more user-friendly and rewarding for our valued contributors! ✨🚀

### Show us the magic with screenshots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@Vaishnavi-Patil2211 your review is appreciated 🙌🏻

**Comment by Vaishnavi-Patil2211** [comment]
Solve the error

**Comment by 0xabdulkhalid** [comment]
Actually there's no error from my side.

**Comment by 0xabdulkhalid** [comment]
@Vaishnavi-Patil2211 i think @Divesh2003 can solve this and merge this PR.

**Pull request merged**
