### PR TITLE
Changed the sytle of buttons(get started,service) in home page  issue-763

### PR DESCRIPTION
**Pull request by ManishaSwain8**
@akshathar-navada I have changed the style and opened this PR as per your instruction under Gssoc 2023.
Do check it out ,if any changes req. : |)

#763 

## Closes

Closes #

## Checklist:

- [ x] I have linked the PR to the correct issue.
- [ x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x ] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @ManishaSwain8 , there is some issue , pls fix it 
image

**Comment by ManishaSwain8** [comment]
Hey @akshathar-navada ,
is there any issue , I got the mail but msg is not here

**Comment by akshathar-navada** [comment]
Oh,,, wait I comment again

**Comment by akshathar-navada** [comment]
This was the issue, pls look into it 
image

**Comment by ManishaSwain8** [comment]
oh ...but in my browser I am getting the correct one.
Screenshot 2023-06-21 185920
Ok I will check if am missing something

**Comment by akshathar-navada** [comment]
Yea, may be some code is overridden ig

**Comment by ManishaSwain8** [comment]
I have opened new pr and checking the conflicts.

**Comment by akshathar-navada** [comment]
Ohh I 👀

**Pull request merged**
