### PR TITLE
updated footer

### LINKED ISSUE #80: Updating footer section
The styling of the footer section can be still improved to make it look more attractive by increasing the space between horizontal columns and changing the styling of icons and links over there. Please let me if I can work on it.

### PR DESCRIPTION
**Pull request by aysal04**
**Description**

This PR fixes #80 

**Notes for Reviewers**
I have updated the styling of footer section. Please review it

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @aysal04 , your commit has conflicts through which we won't be able to merge your PR. So, pls pull the repo properly and then make required changes. And also add required screenshots, so it would be easy for us it review!!

**Comment by aysal04** [comment]
I have resolved the conflicts. Kindly review them. Here are the attached screenshots before and after modifying the styling of the footer:
image (Before)
image (After)

**Comment by akshathar-navada** [comment]
Hey @aysal04 , the current footer is responsive and we prefer that. If there is any other issues, in which u would like to work on please, go ahead!

**Comment by aysal04** [comment]
Yeah. Ig this is also responsive. Anyways will try working on some other issues as well

**Pull request closed without merging**
