### PR TITLE
Image cards

### LINKED ISSUE #831: GSSoC'23: Adding image cards instead of the bulleted institute name in chapters section.
### Current Behavior
image

### Desired Behavior
Adding image cards instead of the bulleted institute name in chapters section.

Example template:

image

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Closes

Closes #831 

## Description

Responsive Image cards added

## Screenshots

image

image

## Checklist:

- [x] I have linked the PR to the correct issue.
-[x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by Divesh2003** [comment]
Hello @ShreyaDhiman24 
Kindly resolve this
Conflicting files
chapters/chapter.html

**Comment by ShreyaDhiman24** [comment]
@Divesh2003  Resolved for this too..

**Comment by Divesh2003** [comment]
@ShreyaDhiman24 

Now also conflicts are there
Conflicting files
assets/css/chapter.css
chapters/chapter.html

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24
> 
> Now also conflicts are there Conflicting files assets/css/chapter.css chapters/chapter.html

@Divesh2003 I have resolved merge conflicts please check again!

**Pull request merged**
