### PR TITLE
Our services

### LINKED ISSUE #853: GSSoC'23: Responsiveness of Our Services Page
### Current Behavior

not responsive

image

image

### PR DESCRIPTION
**Pull request by ShreyaDhiman24**
## Closes

Closes #853 

## Screenshots

[Screencast from 26-06-23 12:30:44 AM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/939836f6-962c-4a2c-bed5-d08a41310076)

## Checklist:

- [x] I have linked the PR to the correct issue.
-  [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x]I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by ShreyaDhiman24** [comment]
@Divesh2003 Resolved.

**Comment by Divesh2003** [comment]
@ShreyaDhiman24 

Now also there are conflicts in chapters/chapter.html

**Comment by ShreyaDhiman24** [comment]
image
..?

**Comment by Divesh2003** [comment]
@ShreyaDhiman24 No

Conflicts are there check
Conflicting files
assets/css/chapter.css
chapters/chapter.html

**Comment by ShreyaDhiman24** [comment]
> @ShreyaDhiman24 No
> 
> Conflicts are there check Conflicting files assets/css/chapter.css chapters/chapter.html

@Divesh2003 Now Check again.

**Comment by Divesh2003** [comment]
@ShreyaDhiman24 Didi Now also conflicts are there 
Conflicting files
assets/css/chapter.css

**Pull request merged**
