### PR TITLE
fixed hover issue

### PR DESCRIPTION
**Pull request by radhikakakkar**
This PR changes he hover colour of the nav links from light purple to the active colour of the list.

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @radhikakakkar , there r conflicts in your commit, through which we won't be able to merge your PR.
Kindly pull the repo properly and then make required changes!! and also required screenshots to review

**Comment by Git21221** [comment]
@radhikakakkar can you please make color name in root and then use a var() to use them? I took a long time to collect all colors and set in root. Thanks :)

**Comment by radhikakakkar** [comment]
Hi @akshathar-navada, where can i see these merge conflicts properly so i can fix them accordingly

**Comment by radhikakakkar** [comment]
> @radhikakakkar can you please make color name in root and then use a var() to use them? I took a long time to collect all colors and set in root.(Still some colors were not added yet) Thanks :)

i will try that and make a new request, thank you

**Pull request closed without merging**
