### PR TITLE
changed the navbar chapter and event style

### PR DESCRIPTION
**Pull request by manoranjanonline**
i am solving by changed the css file#373

**Description**

This PR fixes #

**Notes for Reviewers**

### CODE REVIEW

**Comment by akshathar-navada** [comment]
@manoranjanonline Can u pls add required screenshots

**Comment by manoranjanonline** [comment]
Screenshot (207)

**Comment by manoranjanonline** [comment]
Screenshot (208)

**Comment by akshathar-navada** [comment]
Thanks @manoranjanonline !!

**Pull request merged**
