### PR TITLE
Update chapter.html

### PR DESCRIPTION
**Pull request by akshaya-hub**
solved issue#82

### CODE REVIEW

**Comment by akshathar-navada** [comment]
As I have mentioned we are currently working on separate pages which has to be linked. 
Thank you!

**Comment by akshaya-hub** [comment]
@akshathar-navada I think it's better to remove the link option for chapter colleges for the list of colleges because there is a click option on the college names  when we click we get a new tab with the same page its better to add links to college names or remove the link connection to the names so the users may not disappoint.

**Comment by akshathar-navada** [comment]
It's working in progress. We will surely resolve it. Thank you

**Comment by akshaya-hub** [comment]
@akshathar-navada  can i raise a PR  according to your suggestions

**Comment by akshathar-navada** [comment]
Once, we link the actual college pages, u can improve it 
Thank you @akshaya-hub

**Comment by akshaya-hub** [comment]
@akshathar-navada that's great thank you

**Pull request closed without merging**
