### PR TITLE
assresschanged

### LINKED ISSUE #1558: [Feat]: in contact us section
### What feature?

in the contact us section I would like to change some sections and make it more attractive 

### Show us the magic with screenshots

Screenshot (654)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by khadar1020**
## Closes

Closes #1558

## Description

i have changed the contact us section attractive

## Screenshots

Screenshot (656)

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by khadar1020** [comment]
can you please review my pr @Vaishnavi-Patil2211 and kindly add level3 issue for it

**Comment by khadar1020** [comment]
can you please review my pr @Divesh2003 and kindly add level3 issue

**Comment by khadar1020** [comment]
can you please review my pr @Divesh2003 and kindly add level3 label

**Comment by khadar1020** [comment]
can you please review my pr @Divesh2003 and kindly add level3 label

**Comment by khadar1020** [comment]
can you please review my pr @Divesh2003 and kindly add level3 label

**Comment by khadar1020** [comment]
can you please review my pr @Divesh2003 and kindly add level3 label

**Comment by khadar1020** [comment]
can you please review my pr @Divesh2003 and kindly add level3 label

**Comment by Divesh2003** [comment]
@khadar1020 Hello. For enhancement, Level 2 is added. For new functionality, Level 3 is added

**Comment by khadar1020** [comment]
ok @Divesh2003 thanks for merging

**Pull request merged**
