### PR TITLE
#541 done

### LINKED ISSUE #541: Add greeting bot
### Desired Behavior
"By adding a greeting bot that acknowledges and appreciates pull requests, we can create a positive and motivating environment for contributors."
"The greeting bot's personalized message will make contributors feel valued and encourage them to continue their great work."
"Having a greeting bot in place ensures that contributors receive immediate recognition and assurance that their contributions are being reviewed and appreciated."

### Screenshots / Mockups
image

---

### PR DESCRIPTION
**Pull request by k-deepak04**
Added greeting bot

**Description**

This PR fixes #541 

**Notes for Reviewers**

### CODE REVIEW

**Comment by k-deepak04** [comment]
@akshathar-navada please add respective labels to this :)

**Comment by akshathar-navada** [comment]
Thanks a lot @k-deepak04

**Comment by k-deepak04** [comment]
I should be thanking you for this :)
i will soon create pr for other issues also

**Comment by akshathar-navada** [comment]
> I should be thanking you for this :) i will soon create pr for other issues also

Sure, we will be glad to review and merge it!!

**Pull request merged**
