### PR TITLE
#175 Readme is Updated with badges

### PR DESCRIPTION
**Pull request by shraddha761**
#175

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Thank you @shraddha761 , we will review and merge it soon 🤩

**Comment by akshathar-navada** [comment]
Hey @shraddha761 , there is some problem in your commit. The badges are not updated with current information. It is showing some other random numbers. Can u pls check out this , and resolve

**Comment by shraddha761** [comment]
Okk I'll check

**Comment by shraddha761** [comment]
image

I am getting this error while I push branch

**Comment by shraddha761** [comment]
@akshathar-navada Is the issue is resolved ? This PR is closed

**Pull request merged**
