### PR TITLE
fix: Placeholder Collapsing 🎉

### LINKED ISSUE #1282: Issue with Contact Us Page - Input Field Text and Placeholder Collapsing 📃
**Description:**

**Issue Summary:**
On the Contact Us page, there seems to be a problem with the input fields. When I start typing in any of the input fields, the placeholder text and the input text overlap each other, making it difficult to read what I'm typing. This issue affects the usability of the page and should be addressed.

**Steps to Reproduce:**
1. Go to the Contact Us page.
2. Observe the input fields and their corresponding placeholder texts.
3. Start typing in any of the input fields.

**Expected Behavior:**
The placeholder text should disappear or move above the input text when I start typing, ensuring that the input text remains visible and distinct from the placeholder.

**Actual Behavior:**
When I start typing in the input field, the placeholder text stays in place, causing it to overlap with the input text, making it hard to read what I'm typing.

**Additional Information:**
- Browser: [Include browser name and version]
- Operating System: [Include operating system name and version]
- Device (if applicable): [Include device information if the issue is specific to certain devices]

**Screenshots:**

image

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Closes

Closes #1282 

### **Before**

image

### **After**

[screen-capture.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85815172/700d51df-9d26-4174-b1f1-0827679ab1ed)

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hii @Vaishnavi-Patil2211 👋🏻 Please Review My PR i have Fix your issue 🎉

**Comment by Nishitbaria** [comment]
Hey @Vaishnavi-Patil2211 do you have another issue or other feature that you want?

**Comment by Vaishnavi-Patil2211** [comment]
You can create an issue if you want to do any changes

**Comment by Vaishnavi-Patil2211** [comment]
Also you can work on backend part

**Pull request merged**
