### PR TITLE
email send button modified

### PR DESCRIPTION
**Pull request by harshita-2003**
it was just a normal looking button I have applied css to it

### CODE REVIEW

**Comment by akshathar-navada** [comment]
@harshita-2003 Can u please add a screenshot so that we can review it

**Review by akashgreninja — CHANGES_REQUESTED** [review]
Hey Thanks for contributing to our repository but we cannot accept the readme file changes for now if you contribute your avatar will be added automatically please can you do the required changes

**Comment by harshita-2003** [comment]
oh sorry I did removed my avatar from readme , do look at the changes in policy.html 
EARLIER:(not matching color theory):::::::::
Screenshot 2023-05-21 163809

now :
Screenshot 2023-05-21 164006

Screenshot 2023-05-21 164353

**Comment by akshathar-navada** [comment]
@harshita-2003 The existing branches has conflicts through I won't be able to merge it, please pull the repo propeerly and then make necessary changes.
And let the image near table of contents be as it is, please don't alter that

**Pull request closed without merging**
