### PR TITLE
added slider to accomplishments

### PR DESCRIPTION
**Pull request by amisha-shrivastava**
**Description**

This PR fixes the Our Accomplishments section by adding the sliders allowing users to easily navigate through the accomplishments. The swiper component is used to do the same.

image

**Notes for Reviewers**

### CODE REVIEW

**Comment by Divesh2003** [comment]
@amisha-shrivastava some branch conflicts are there. Kindly resolve it....

**Review by amisha-shrivastava — COMMENTED** [review]
please check .

**Comment by amisha-shrivastava** [comment]
@Divesh2003 I've resolved the conflict. Kindly review it.

**Comment by gurjeetsinghvirdee** [comment]
Kindly add level labels on this PR @Divesh2003

**Pull request merged**
