### PR TITLE
zoom in effect and italics

### PR DESCRIPTION
**Pull request by shramanpaul**
Zoom in effects added while hovering to the **_"Number says it all"_** section and italicized the _**"_Multi-college Tech"_**_ in "_Who we are?_" section.

### CODE REVIEW

**Review by akshathar-navada — CHANGES_REQUESTED** [review]
@shramanpaul This branch has conflict for which we can't merge your PR, can u please pull the repo properly and then resolve issue!

**Comment by shramanpaul** [comment]
The changes have been done and the  conflict has been resolved i have also created the a new pull request with same changes if the issue persists in this you can add that one

**Comment by akshathar-navada** [comment]
The original styles was not shown , so I reverted back.  Mainly hovering effect in about us section was not functional, and the background was white in the count section.

**Comment by shramanpaul** [comment]
@akshathar-navada my contribution for this part is present in the project but my name is not present in your contributors list in github.

**Pull request merged**
