### PR TITLE
Image

### LINKED ISSUE #665: Enhancing the view of the images in "why choose us " section
### Current Behavior
Just now the images in this section are looking very dull, I would like to add some CSS styling to these images which will make them look more attractive

### Desired Behavior
I will add hovering effect and border to the images

### Screenshots / Mockups
Screenshot (41)

**Kindly assign me this issue under GSSOC'23**

---

### PR DESCRIPTION
**Pull request by smritimangal26**
## Closes

Closes #665 

 Example: Closes #665 

## Description

Added border and hover effect to the image

## Screenshots

Screenshot (62)

## Checklist:

- [.] I have linked the PR to the correct issue.
- [.] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [.] I have built and tested the changes, and they do not break or show any errors.

Thank you for contributing to OSCodeCommunitySite! 

Contributing Conventions:

1. Include descriptive PR titles with [<component-name>] prepended.

By following the community's contribution conventions upfront, the review process will 
be accelerated and your PR merged more quickly.
-->

### CODE REVIEW

**Comment by smritimangal26** [comment]
kindly review it

**Comment by akshathar-navada** [comment]
Hey , hovering effect is not required for those. If there is anything else, u would like to work on, pls go ahead!

**Comment by smritimangal26** [comment]
I have also added the border not just the hovering effect

**Comment by akshathar-navada** [comment]
It will be like extra, it's not required

**Comment by smritimangal26** [comment]
okay no problem

**Pull request closed without merging**
