### PR TITLE
Consistent Hover Effect In All Sections Of Website 

### LINKED ISSUE #771: Consistent Hover Effect In All Sections Of Website
### Current Behavior
Every section of the website i.e. "Numbers say it all", "Accomplishments", "Join Us", "Testimonials" have different hover effects which is creating disruption in overall design of the website. 

### Desired Behavior
Making one kind of hover effect in all above mentioned sections will create strong impact on the design of the website.

### Screenshots / Mockups
Addition of "Join Us" section's hover effect(movement inward) in all section of the website. It is shown in the first two boxes of below mentioned screenshot.
oscode (3)

### PR DESCRIPTION
**Pull request by iamRabia-N**
## Closes
This PR contains the updated code for the consistent "Hover Effect" in all sections of the website. This PR is the result of the following issue:
Consistent Hover Effect In All Sections Of Website #771
Closes #771

## Description
Consistent hover effect in all sections of the website.
## Screenshots
**Numbers say it all Section** 
oscommunity-pr (4)
**Accomplishments Section**
oscommunity-pr (3)
**Join Us Section**
oscommunity-pr (2)
**Testimonials Section**
oscommunity-pr (1)

## Note to reviewers
Kindly share your valuable feedback or any suggestions for more good improvement in the following issue.

## Checklist:
- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @iamRabia-N , the hovering effect was more, especially in accomplishment section. We prefer the existing one,so ahd to revert back!

**Comment by iamRabia-N** [comment]
We can remove only accomplishment section hover effect if you don't want it.

**Comment by iamRabia-N** [comment]
> We can remove only accomplishment section hover effect if you don't want it.

@akshathar-navada

**Comment by akshathar-navada** [comment]
Okay, fine and also don't give so much transition has the current one!

**Comment by iamRabia-N** [comment]
Great. Now, we have 2 options:
1. Adding transitional hover effect on all sections except "Accomplishment"
2. Border based hover effect on all section like the hover effect of Accomplishment section.
Select any of these that you think best suit on the website.

**Comment by akshathar-navada** [comment]
1st one

**Pull request merged**
