### PR TITLE
feat: Init the Auto Generate Changelog workflow. ⚡

### LINKED ISSUE #1338: Automated Workflow for Generating Conventional Logs in Project Version Control ✨
**Description:**
In modern software development, version control is essential for tracking changes, collaborating efficiently, and maintaining code quality. To promote adherence to established coding standards and improve code readability, many development teams adopt the Conventional Commit standard for version control. However, the process of manually creating and maintaining Conventional Logs for each version can be time-consuming and error-prone.

The aim of this project is to design and implement an automated workflow that seamlessly generates Conventional Logs for conventional versions of the project. This automation process will streamline the recording of version changes in a consistent format and enable developers to better understand the history of the project.

**Key Objectives:**
1. Automated Commit Message Validation: Develop a mechanism to validate commit messages against the Conventional Commit format, ensuring they adhere to the established standards.

2. Version Tracking and Tagging: Implement a system that automatically tracks and tags conventional versions based on the commit history, simplifying the identification and retrieval of specific versions.

3. Automated Log Generation: Create a script or tool that automatically generates Conventional Logs for each version by extracting relevant commit information and organizing it into a human-readable format.

4. Changelog Integration: Integrate the automated Conventional Log generation process with existing changelog tools or systems to ensure seamless updating of the project's release notes.

5. Error Handling and Reporting: Implement a robust error-handling mechanism to identify and address any issues that may arise during the automated workflow, providing clear and informative error reports to aid in debugging.

6. Configurability and Customization: Allow developers to customize the workflow according to their project's specific requirements, including the ability to exclude certain commits or add supplementary information to the generated logs.

7. Documentation and Training: Provide comprehensive documentation and training resources to guide team members on how to use and contribute to the automated Conventional Log workflow effectively.

### PR DESCRIPTION
**Pull request by Nishitbaria**
## Closes

Closes #1338

## Screenshots

image

## Checklist:

- [x] I have linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
hey @Vaishnavi-Patil2211  Please Review the Pr and Merge it

**Comment by Vaishnavi-Patil2211** [comment]
Not able to merge your pr

**Comment by Nishitbaria** [comment]
@Vaishnavi-Patil2211  hey can you show me a screenshot ?

**Comment by Nishitbaria** [comment]
> Referenc

@Vaishnavi-Patil2211  hey can you show me a screenshot ?

**Comment by Nishitbaria** [comment]
Hey @Vaishnavi-Patil2211 It's Not a Problem from My Side If you Facing any problems check out this article:https://jessehouwing.net/cannot-push-to-github-without-workflow-scope/

**Pull request closed without merging**
