### PR TITLE
Header UI updated #230

### PR DESCRIPTION
**Pull request by KashiwalHarsh**
I have Updated the UI of the header on the homepage with an underline effect on hover instead of changing the color of the link (see screenshot). I have also added a linear gradient to the background image as the text in front was not visible. I have done minimal changes to the code the result is responsive too. #230

NOTE: other pages like chapters and events are still on the old header UI if you liked this UI I can update them too in another PR

look

### CODE REVIEW

**Comment by akshathar-navada** [comment]
Hey @KashiwalHarsh , this looks great. Your commit has few conficts through which we won't be able to merge. Can u pls pull the repo properly and then make required changes.
Yes and pls apply this styling of navbar to other pages too:)

**Comment by KashiwalHarsh** [comment]
Hii @akshathar-navada, I have resolved the issue you can check. You can merge it for now 
And I will apply the same header UI to other pages too on a different pull request 

Do let me know if there is any issue

**Comment by akshathar-navada** [comment]
> 

Hey, when u run 'npm install' it keeps track of the exact versions of the installed packages. The changes are legitimate and necessary due to updates or changes in the dependencies of your project. Don't worry, it won't affect to the project.
Other thing what u can do is, instead of running npm install, u can directly to navigate to http://localhost:5000/, so by this the versions currently present in the code won't change. 
Anyways, it's fine . If there is any issues I will let uk.

Thanks for your contribution @KashiwalHarsh , we will review and merge it soon!!

**Comment by KashiwalHarsh** [comment]
Hey @akshathar-navada I want to make some more UI changes to the website. This was my first Pull request that got merged thankyou for that.

**Pull request merged**
