### PR TITLE
#666 whoweare(UI Improve)

### LINKED ISSUE #666: Alignment of the "who we are" section
### Current Behavior
Currently, the heading is left aligned while the rest of the headings are centrally aligned

### Desired Behavior
I would like to make it centered aligned

### Screenshots / Mockups
Screenshot (42)

**kindly assign me this issue under GSSOC'23**

---

### PR DESCRIPTION
**Pull request by smritimangal26**
## Closes 666

Closes #666  

## Description
Changed the alignment of the heading and also fixed the position of image and paragraph

## Screenshots

Screenshot (45)

## Note to reviewers

please review my work 

## Checklist:

- [. ] I have linked the PR to the correct issue.
- [ .] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [ .] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by smritimangal26** [comment]
Thanks for reviewing, I will make the suggested changes

**Comment by smritimangal26** [comment]
I have done the suggested changes kindly have a look 

Screenshot (47)

**Comment by akshathar-navada** [comment]
The spacing is fine, but just look the image once, it is like squezzed na..Pls adjust the height , incraese it and try to make it look as of existing image

**Comment by smritimangal26** [comment]
Actually the size of image is same as the original code , I have just added the padding to the top, left and bottom of the image 
and beacuse of padding the image is looking sequezzed

**Comment by smritimangal26** [comment]
**Kindly see the full screen view of the screenshot** by clicking on the ss
as the screenshot is not doing the justice to the image

image
 I have done the changes and now the picture looks clear and also this shape is looking better than the old one 
Please review it and than only I will raise the PR for it ,

**Comment by akshathar-navada** [comment]
Yep! it looks great. U can open a PR @smritimangal26

**Comment by smritimangal26** [comment]
Thanks for reviewing 
I have opened the PR

**Pull request merged**
