### PR TITLE
Improve visual structure of Navbar to make it more appealing and responsive

### PR DESCRIPTION
**Pull request by sanketsaurav2411**
Hi @peb-peb @akshathar-navada,
Made all necessary changes as per issue #45 raised.
-Added Glassmorphic effect (modified blur effect, earlier it was restricting mobile navbar layout)
-Responsive Navigation bar (earlier Navbar doesn’t work in mobile view) 
-Changed font in navbar

Now, Navbar works completely fine in mobile.

Screenshot After clicking on Navigation Icon (earlier):
Screenshot 2023-05-21 014530

Screenshot After clicking on Navigation Icon (now):
Screenshot 2023-05-21 014547

Glassmorphic effect:
Screenshot 2023-05-21 015026

### CODE REVIEW

**Comment by sanketsaurav2411** [comment]
[Resolved]: Few alignment issues have also been resolved.

**Comment by akshathar-navada** [comment]
Thank you @sanketsaurav2411 ,we will soon review and merge PR

**Comment by sanketsaurav2411** [comment]
> @sanketsaurav2411 We prefer the nav bar blur effect, instead of glassmorphic. So, can u please change that effect. Other changes which u have done is fine:)

Hey @akshathar-navada,
If I change it to blur effect i.e. `backdrop-filter: blur(1rem);` it will restrict the `.navbar-mobile .dropdown ul` to header only, meaning the navbar-menu will be restricted to header part only.
This is the reason why I have used:
`/*------------------------------------------
# GLASSMORPHIC EFFECT 
------------------------------------------*/
.glassmorphic {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 100;
  overflow: hidden;
}

.glassmorphic::before {
  content: "";
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  backdrop-filter: blur(1rem);
  z-index: -1;
}

.glassmorphic::after {
  content: "";
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: rgba(0, 0, 0, 0.1); /* Adjust the background color and transparency as desired */
  z-index: -2;
}`

This handles the `.navbar-mobile .dropdown ul` as well.

Also it provides blur effect to, so visually there is no any significant change in it.

Screenshots:
image

If we don't add before and after rules, After clicking on Navigation Icon  `.navbar-mobile .dropdown ul` will be like:
Screenshot 2023-05-21 014530

Thank You :)

**Comment by akshathar-navada** [comment]
Ok cool! @sanketsaurav2411 , thanks for your contribution :)

**Pull request merged**
