### PR TITLE
Size of discord icon now increasing on hovering in the footer of front-page

### LINKED ISSUE #654: The discrod icon in the footer of front page is not increasing in size on hovering
### Description

The discord icon in the footer of front-page is not increasing in size on hovering over it. All other social media icons are increasing in size but only discord icon is not increasing in size.
### Expected Behavior

I can solve this task. Can you please assign this issue to me?
### Screenshots

WhatsApp Image 2023-06-08 at 22 40 14
WhatsApp Image 2023-06-08 at 22 40 07

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

### PR DESCRIPTION
**Pull request by Shreyans2004**
## Closes

Close #654

## Description
Previously on hovering above the discord icon ,it was not increasing in size in the footer of front-page. Now it is increasing in size on hovering. Now can it be merged?

## Checklist:

- [x] I have linked the PR to the correct issue.
- [ ] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [x] I have built and tested the changes, and they do not break or show any errors.

### CODE REVIEW

**Comment by akshathar-navada** [comment]
There was some issue, when merge, so reverted back

**Comment by Shreyans2004** [comment]
What i should do now? Do I have to make new changes to code in order to resolve the issue?

**Comment by akshathar-navada** [comment]
Btw I don't think through changing the bootstarp logo to font awesome, makes the discord hovering proper, do check once, If it is resolved u can open a new PR, pls pull the repo properly before making any changes!

**Comment by Shreyans2004** [comment]
Now I have checked and changing bootstrap logo to font-awesome makes the hover proper.I have created a new pull request #687.Can you please check that?

**Pull request merged**
