### PR TITLE
modified the search-bar and suggetions and in terms of styling

### PR DESCRIPTION
**Pull request by An525ish**

### CODE REVIEW

**Comment by akshathar-navada** [comment]
@An525ish PLease add required screenshots, and there are many conflicts in your branch, for which we can' t merge, please pull the repo properly and then do required changes

**Comment by An525ish** [comment]
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/93612051/b25121c6-475c-4d48-854a-e200efc3ff6b

**Comment by An525ish** [comment]
> @An525ish PLease add required screenshots, and there are many conflicts in your branch, for which we can' t merge, please pull the repo properly and then do required changes

here is the video of the search bar ... there is a smooth transition in the search bar for scaling and for showing the results but for some reason it's not properly showing in the video

**Comment by akshathar-navada** [comment]
Awesome @An525ish , we will review and merge it soon:)

**Pull request merged**
